spring:
  datasource:
    # H2 en memoria (sirve local y en Render)
    url: jdbc:h2:mem:microcursosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # De momento dejamos Mongo sin URI expl√≠cita.
  # data:
  #   mongodb:
  #     uri: mongodb://localhost:27017/microcursosdb

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: "CAMBIA_ESTO_POR_UNA_CLAVE_LARGA_Y_UNICA_1234567890"
    expiration: 3600000   # 1 hora
